[workspace]
members = [
    ".",
    "benchmark",
]

[package]
name = "rembed"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.release]
debug = true


[[bench]]
name = "fruitfly_8"
harness = false
