[workspace]
members = [
    ".",
    "benchmark",
]

[package]
name = "rembed"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap = "0.7.0"
nalgebra = "0.33.2"
ordered-float = "5.0.0"
rstar = "0.12.2"
sha2 = "0.10.9"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[profile.release]
debug = true


[[bench]]
name = "fruitfly_8"
harness = false
